### ISSUE TITLE
Call to undefined method NotificationChannels\Bandwidth\BandwidthMessage::create()

### ISSUE THREAD

**Issue by hemendraajmera** [ankurk91/bandwidth-notification-channel#13]
I am new to bandwidth SMS Gateway. i want to use in laravel 6. i tried as given instruction but not get works.
can you help to work properly 
this error comes when i used 
Call to undefined method NotificationChannels\Bandwidth\BandwidthMessage::create()

**Comment by ankurk91** [comment]
https://github.com/ankurk91/bandwidth-notification-channel/blob/master/src/BandwidthMessage.php#L17

**Comment by ankurk91** [comment]
You can return string as well, like

```php
public function toBandwidth($notifiable)
    {
        return "You message here";
    }
```

**Comment by ankurk91** [comment]
You should install the version 3.x of this package
```
composer require ankurk91/bandwidth-notification-channel:^3.0
```

You can read the v3.0 docs here
https://github.com/ankurk91/bandwidth-notification-channel/tree/faad361c3479095f5d44fe2a54342197ab74d28d

**Comment by hemendraajmera** [comment]
Ok
